---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for deploying a website on AWS'

Parameters:
  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro

Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.100.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for website access
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  LaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
      - !Ref MySecurityGroup
      KeyName: !Ref KeyName
      ImageId: ami-0c94855ba95c574c8 # This is the latest Amazon Linux 2 LTS AMI as of writing
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install -y apache2 unzip
          sudo rm /var/www/html/index.html
          wget https://bpsdynamic.s3.eu-west-1.amazonaws.com/website.zip -P /var/www/html/
          sudo unzip /var/www/html/website.zip -d /var/www/html/
          sudo service apache2 restart

  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      MinSize: '2'
      MaxSize: '4'
      LaunchConfigurationName: !Ref LaunchConfiguration
      LoadBalancerNames:
      - !Ref LoadBalancer
      VPCZoneIdentifier: 
      - !GetAtt MySubnet.SubnetId

  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      Subnets:
      - !Ref MySubnet
      SecurityGroups:
      - !Ref MySecurityGroup

  MySubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: eu-west-1a
      VpcId: !Ref MyVPC
      CidrBlock: 10.100.1.0/24
